baseURL = "https://mikedovale.com/"
title = "The Photography of Miguel Dovale"
languageCode = "en"
defaultContentLanguage = "en"
timeZone = "Europe/Berlin"
timeout = "120s"
theme = "hugo-theme-gallery"

copyright = "© 2025 Miguel Dovale"
disableKinds = ["taxonomy"]
enableRobotsTXT = true

[pagination]
  pagerSize = 12

[params]
  defaultTheme = "dark"
  description = "A collection of favorite photographs."
  title = "Miguel Dovale"
  customCSS = ["css/custom.css"]

  [params.author]
    name = "Miguel Dovale"
    email = "mikedovale.gloss999@passinbox.com"

  [params.socialIcons]
    instagram = "https://www.instagram.com/mikedovale"
    github = "https://github.com/mdovale"
    email = "mailto:mikedovale.gloss999@passinbox.com"
    # Optional ones, uncomment if you want later:
    #website = "https://mikedovale.com"
    #flickr = "https://www.flickr.com"
    #500px = "https://500px.com"

  [params.gallery]
    # boxSpacing = 10  # Uncomment to adjust justified layout spacing
    # targetRowHeight = 288
    # targetRowHeightTolerance = 0.25

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 100
  resampleFilter = "CatmullRom"

  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"

  [[module.imports]]
    path = "hugo-theme-gallery"

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Project: Saruuliña"
    url = "/saruuliña"
    weight = 1

  [[menu.main]]
    name = "Project: Andrea"
    url = "/andrea-2020"
    weight = 2

  [[menu.main]]
    name = "Project: Boomtown"
    url = "/boomtown-2017-2018"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 3

  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/mdovale"
    weight = 3

[services]
  [services.rss]
    limit = 100