baseURL = 'https://mikedovale.com/'   # <-- Your real domain or GitHub Pages URL
languageCode = 'en-us'
title = 'Mike Dovale Photography'
theme = 'hugo-theme-gallery'
[pagination]
  pagerSize = 12

[params]
  title = "Mike Dovale Gallery"
  description = "A collection of my favorite photographs."
  copyright = "© 2025 Mike Dovale"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1